# Generated by Django 5.1.1 on 2024-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="customer_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="order_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
                ("item_name", models.CharField(max_length=100, null=True)),
                ("item_quantity", models.IntegerField(null=True)),
                ("item_price", models.IntegerField(null=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
